### ISSUE TITLE
`optional_callbacks` is not ignored by default

### ISSUE THREAD

**Issue by vkatsuba** [AdRoll/rebar3_hank#112]
Hi All,

Not Sure if this correct but looks like no make sense to validate `optional_callbacks` because the `optional_callbacks` design is exists  for those cases when it is possible not to use callbacks in modules where behavior defined or used.

Regards,
--V

**Comment by elbrujohalcon** [comment]
Hi @vkatsuba,

I'm not sure what you mean by this. Do you have an example?

I'll take a very wild guess and speculate that you're referring to a module like this…

```erlang
-module(my_mod).

-callback used_callback() -> ok.
-callback unused_callback() -> ok.
-optional_callbacks [unused_callback/0].

-export([usage/1]).

usage(Module) -> Module:used_callback().
```

That module will emit a warning since `unused_callback/0` is unused.
And, according to the rule definition (which is based on [this article](https://link.medium.com/g8Q0CalkQfb)), the warning is *correct*.
The optional callbacks are _optional_ for the modules that _implement_ the behavior, not for the module that _defines_ it.

**Comment by vkatsuba** [comment]
Closed as expected behavior.
