### ISSUE TITLE
Dynamically used app env reported as unused

### ISSUE THREAD

**Issue by gomoripeti** [AdRoll/rebar3_hank#127]
## Bug Description
An app env that is assigned in sys.config or app.src is reported as unused which is used in the way described in the "reproduce" seciotn

## To Reproduce

We have a library which has a call like below
```
f(AppName) ->
  application:get_env(AppName, env_key).
```
That library is used by a top level app, which has `env_key` set in `<appname>.app.src`

## Expected Behavior
If hank encounters a call `application:get_env(Var, env_key)` and it cannot determine the values of `Var`, it shouldn't report `env_key` as unused for any app in the project.

## `rebar3` Logs
```
$ DEBUG=1 rebar3 hank
...
===> Looking for code to kill with fire...
===> Hank rules: [single_use_hrl_attrs,single_use_hrls,
                         unnecessary_function_arguments,unused_callbacks,
                         unused_configuration_options,unused_hrls,
                         unused_macros,unused_record_fields]
===> Hank Context: #{app_dirs =>
                                #{<app_name> =>
                                      "path/to/app_name"},
                            project_apps => [<app_name>]}
===> Hank will use 45 files for anlysis: ["apps/<app_name>/...", ...]
```

One thing that is strange is that the files used for analysis does not include files in deps. Maybe that's the real issue?

## Additional Context
 - OS: MacOS
 - Erlang version: 21.3.8.2
 - rebar3 version: 3.13.2

**Comment by pbrudnick** [comment]
Thank you @gomoripeti and welcome!

Could you please put the warning/s? that output looks incomplete.

**Comment by paulo-ferraz-oliveira** [comment]
@pbrudnick, the output also mentions `anlysis` (might be worth including in the "fix")...

**Comment by elbrujohalcon** [comment]
@gomoripeti So, you have an application that expects to find an environment variable in a different application that uses it as a dependency.

My first reaction to that would be… **Why?** Why would you do such a thing?
To be fair, we used to have similar things in some of our systems. @miriampena will remember them for sure 😝 . But they are generally a bad idea, there is usually a far better way of achieving the same effect.

My second remark would be related to your question about why the anlysis (🤦‍♂️) doesn't include dependencies. We make that decision because we don't want to emit warnings for things you can't fix. So… we can't analyse code in your dependencies. To analyse that code, just run hank on them. The actual thought process behind this was far more elaborate and complex, but in a nutshell: We didn't expect, for instance, a dependency to impose a rule on how you should structure your application configuration.

That is all to say that I don't think we'll _fix_ this issue. I would be more inclined to treat this as we treat the callback implementation rule: Adding documentation to the `unused_configuration_options` rule stating that…

> For this rule to apply, it's assumed that configuration options for an Erlang application are only consumed within said Erlang application or the other applications in the same umbrella project.
> If you have a dependency that consumes an environment parameter from one of your project applications, you can add an ignore rule in `rebar.config` for it.

**Comment by gomoripeti** [comment]
thanks all, this all makes sense. Documenting the assumptions, and this way encouraging good code structure is very good.

(I tried hank, first time, with zero config, zero assumptions, let's see what it finds. Brujo encouraged in his conf talk to report any unexpected warnings. I think now that the assumptions of the rules are documented, it's much clearer what to expect, and when to add ignore-config. For legacy code, which we really want to fix, at the end of a long backlog)

Btw checking app env entries is a great idea, it's more than I expected from a dead-code killer.
The first run (although I did not find any real dead code) but helped me add some missing behaviour attributes, so pushes towards good coding practices.
Great tool overall!
