### ISSUE TITLE
We still need a better way to suppress unused ignores

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_hank#165]
## Is your feature request related to a problem? Please describe.
After #163 was "fixed", we can either ignore _all_ unused ignores or none of them.
That's not enough for this to be useful. Sometimes we just want Hank to fully ignore an entire folder (like `a/path/where/we/copied/otp/for/whatever/reason/**/*`). We can't be more specific there, we just want to ignore **all** warnings for it, the ones that can be emitted and the other ones, too.

## Describe the solution you'd like
I'm not entirely sure what the proper solution should be. Maybe don't notify about unused ignores if the ignore is just a wildcard (i.e. what @paulo-ferraz-oliveira suggested on #163 originally), but then… what about `-hank ignore.`. Is it ok to still let the users know that they can be more specific with the warnings in that file (i.e. tell them about the unused rule ignores that such an attribute is provoking)?

My gut feeling is that ☝🏻 solution is the best tradeoff between the easiness of code and the usefulness of the feature. I hear/read opinions. 👂🏻

**Comment by pbrudnick** [comment]
I'd ignore warning this rule for all the files explicitly using `-hank ignore` and for all the files ignored via config.

Semantically, those rules might be understood like "ignore hank for these files" instead of "ignore all the hank rules for these files", so in that sense, it's ok to don't warn on those.
But if you are only ignoring one or more rules, it might be ok to these files be checked by hank and prevent about unused ignores.

Other partial (and more dificult?) solution could be to check this rule for files explicitly ignored with `-hank ignore`, but warn about rules that could be ignored, and not unused ones, to avoid doing this calculation:
all_the_rules -- unused_rules = rules_I_have_to_ignore
But perhaps it could be a different rule...
