### ISSUE TITLE
[unnecessary_function_arguments] Add callbacks checks

### ISSUE THREAD

**Issue by pbrudnick** [AdRoll/rebar3_hank#40]
Related to https://github.com/AdRoll/rebar3_hank/issues/8
Avoid ignoring files which implement behaviours but check their internal functions are not callbacks.

**Comment by elbrujohalcon** [comment]
Some ideas…

### Handling *known* behaviors
Instead of just checking if the file has a behaviour attribute…
1. collect all the behaviors that the file implements.
2. for each one of them evaluate `Behavior:behaviour_info(callbacks)` and collect all the resulting tuples in a single list.
3. if that call fails, ignore the whole module (because we can't be sure which functions are callbacks).
4. If that call works, only ignore the functions in the list.

### Handling *all* behaviors
Just like the one above but, for each of the modules that fail in `2`…
1. Check the list of files to analyze in search for the module.
2. If the module is not there, ignore the whole file (we can't be sure which functions are callbacks).
3. If the module is there…
3.1. collect all `callback` attributes.
3.2. analyze them with `erl_syntax_lib`.
3.3. turn them into `{Name, Arity}` tuples.
3.4. add them to the list obtained in the item `2` and keep moving from there.
